### ISSUE TITLE
When no scope is selected  the user cannot go through with the creation of its initiative

### ISSUE THREAD

**Issue by virgile-dev** [OpenSourcePolitics/decidim-module-initiatives_nosignature_allowed#1]
User as to complete its initiative in step 3
<img width="508" alt="Capture d’écran 2020-03-16 à 17 36 03" src="https://user-images.githubusercontent.com/11473995/76780374-3a19e480-67ad-11ea-9e0c-c8fec2bcfda4.png">
If the user doesn't select a scope he will get this error and won't be able to proceed
<img width="1202" alt="Capture d’écran 2020-03-16 à 17 34 36" src="https://user-images.githubusercontent.com/11473995/76780370-37b78a80-67ad-11ea-9dcf-8fd3892ba000.png">

**Comment by armandfardeau** [comment]
Hi @virgile-dev, I'm transferring this issue to Decidim because this is not a problem with this module, as you can see, when you have not selected a scope there cannot be a type associated, hence the error.
